In [1]:
#Importing numpy library
import numpy as np

# Creating and Reshaping Array's

In [2]:
#First arrayrank 1
first_numpy_array=np.array([25,35,65,75])
print(first_numpy_array)

[25 35 65 75]


In [3]:
#array with zeroes
numpy_zeroes_array=np.zeros([3,5,2])
print(numpy_zeroes_array)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [4]:
#array with ones
numpy_onces_array=np.ones([3,3,3])
print(numpy_onces_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
#empty array with random numbers
numpy_empty_array=np.empty([4,3])
print(numpy_empty_array)

[[4.45057637e-308 1.78021527e-306 8.45549797e-307]
 [1.37962049e-306 1.11260619e-306 1.78010255e-306]
 [9.79054228e-307 4.45057637e-308 8.45596650e-307]
 [9.34602321e-307 4.94065646e-322 3.73623052e-061]]


In [6]:
#array created with arrange method
np_arrange=np.arange(5,21,0.5)
print(np_arrange)

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5
 19.  19.5 20.  20.5]


In [22]:
#using Shape method
np_arrange.shape

(32,)

In [23]:
#Using Reshape method
np_arrange.reshape(4,8)

array([[ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5],
       [13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5]])

In [24]:
#using linspace method
np_linspace=np.linspace(20,40,2)
print(np_linspace)

[20. 40.]


In [25]:
#using ndim to identify dimensions of an array
np_linspace.ndim, numpy_onces_array.ndim

(1, 3)

In [26]:
#using shape to identify shape (dim,length, bredth of the array)
np_linspace.shape,numpy_zeroes_array.shape

((2,), (3, 5, 2))

In [27]:
#using size to identify element count in an array
np_linspace.size,numpy_zeroes_array.size

(2, 30)

In [12]:
#using dtype to identify element data type in an array
np_linspace.dtype,numpy_zeroes_array.dtype

(dtype('float64'), dtype('float64'))

# Various operators in Numpy

In [28]:
#creating example array's for conducting operations
list1=np.array([2,3,4,5,6,7,8])
list2=np.array([10,11,12,13,14,15,16])

## Using Mathematical Operations in Array's

In [29]:
#addition
added=np.add(list1,list2)
print(added)

[12 14 16 18 20 22 24]


In [30]:
#subtraction
subtracted=np.subtract(list2,list1)
print(subtracted)

[8 8 8 8 8 8 8]


In [31]:
##Multiply

#multiply with constant
multipp=list1*10

#multiply array's
multyy=list1*list2

print(multipp,multyy)

[20 30 40 50 60 70 80] [ 20  33  48  65  84 105 128]


## Using Comparision Operations in Array's

In [17]:
#Posting array's again for visibility
#list1=np.array([2,3,4,5,6,7,8])
#list2=np.array([10,11,12,13,14,15,16])

In [18]:
#using Greater than
list1[list1>5]

array([6, 7, 8])

In [19]:
#using less than
list2[list2<14]

array([10, 11, 12, 13])

In [33]:
list1[list1!=4]

array([2, 3, 5, 6, 7, 8])

## Using Logical Operations in Array's

In [43]:
#Posting array's again for visibility
#list1=np.array([2,3,4,5,6,7,8])
#list2=np.array([10,11,12,13,14,15,16])

In [37]:
#Using 'AND' Method
np.logical_and(list1>3,list1<12)

array([False, False,  True,  True,  True,  True,  True])

In [44]:
#Using 'OR' Method
np.logical_or(list2>15,list2<12)

array([ True,  True, False, False, False, False,  True])

In [46]:
#Using 'NOT' Method
np.logical_not(list2<12)

array([False, False,  True,  True,  True,  True,  True])

## Accessing Array's 

In [74]:
#Creating 2D array for Accessing learning
list2d=np.array([list1,list2])
list2d

array([[ 2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16]])

In [77]:
#Accessing a particular row or dimension
list2d[1]

array([10, 11, 12, 13, 14, 15, 16])

In [80]:
#Accessing a element in the array
list2d[1,4]

14

In [82]:
#Accessing a column of elements
list2d[:,3]

array([ 5, 13])

In [84]:
#Accessing few columns of elements
list2d[:,2:4]

array([[ 4,  5],
       [12, 13]])

In [95]:
#Copying the dataset
list2d=list3d.copy()

## Using Shape Manipulation Fucntions in Array's 

In [136]:
sh_list1=np.array([2,3,4,5,6,7,8,9,0,1])
sh_list2=np.array([11,12,13,14,25,16,17,18,19,20])
sh_list2d=np.array([sh_list1,sh_list2])

In [137]:
#Using Ravel function to flatten the array into a single row
sh_list2d.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9,  0,  1, 11, 12, 13, 14, 25, 16, 17,
       18, 19, 20])

In [138]:
#Using reshape function to change the dimension of the array
sh_reshape=sh_list2d.reshape(4,5)
print(sh_resize)

None


In [139]:
#Using hstack function
sh_stack=np.hstack((sh_list1,sh_list2))
print(sh_stack)

[ 2  3  4  5  6  7  8  9  0  1 11 12 13 14 25 16 17 18 19 20]


In [140]:
#Using Transpose function
sh_transposed=sh_list2d.transpose()
sh_transposed

array([[ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 25],
       [ 7, 16],
       [ 8, 17],
       [ 9, 18],
       [ 0, 19],
       [ 1, 20]])

In [170]:
#Using trace to find sum of diagonal elements
arr_trace=np.array([[1,3],[7,6]])
sh_trace= np.trace(arr_trace)
print(sh_trace)

7
